# Generated by Django 2.1.5 on 2020-09-23 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 12, 57, 34, 646254), verbose_name='date published'),
        ),
    ]
